name: Create awesome badges

on:
  push:
    branches:
      - main

jobs:
  create_awesome_badges:
    name: Create badges
    runs-on: ubuntu-latest
    steps:
      - name: Get Python version
        run: echo 'PYTHON_BADGE=sh -c "python ../../scripts/get_python_version.py"' >> $GITHUB_ENV
      - name: Create Python Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ed2161fd4d8343928522cb6cbfa809ce
          filename: selenium-pom-python-badge.json
          label: python
          message: ${{ env.PYTHON_BADGE }}
          color: "#3776AB"
          namedLogo: "Python"

      - name: Get pytest version
        run: echo 'PYTEST_BADGE=sh -c "python ../../scripts/get_pytest_version.py"' >> $GITHUB_ENV
      - name: Create pytest Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: d9ce1966b3b9a3efa15409b1314b5cc6
          filename: selenium-pom-pytest-badge.json
          label: pytest
          message: ${{ env.PYTEST_BADGE }}
          color: "#0A9EDC"
          namedLogo: "Pytest"

      - name: Get Selenium version
        run: echo 'SELENIUM_BADGE=sh -c "python ../../scripts/get_selenium_version.py"' >> $GITHUB_ENV
      - name: Create Selenium Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 8b02604366dd2f09945ab392895d2b07
          filename: selenium-pom-selenium-badge.json
          label: selenium
          message: ${{ env.SELENIUM_BADGE }}
          color: "#43B02A"
          namedLogo: "Selenium"

      - name: Get Allure version
        run: echo 'ALLURE_BADGE=sh -c "allure --version"' >> $GITHUB_ENV
      - name: Create Allure Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ca107f1f3280bf38a227b90018e44d9f
          filename: selenium-pom-allure-badge.json
          label: allure
          message: ${{ env.ALLURE_BADGE }}
          color: "green"
